apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: my-nginx-pod
      labels:
        app: nginx
    spec:
        containers:
        - name: my-nginx-container
          image: nginx
          ports:
          - containerPort: 80