apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # group together pods that match this selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
